{{- if .Values.istio.enabled }}
{{- range $key, $gateway := .Values.istio.gateways }}
{{- if ne ($gateway.enabled | toString) "false" }}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "golden-chart.istioGatewayName" (dict "context" $ "gatewayKey" $key) }}
  namespace: {{ include "golden-chart.namespace" $ }}
  labels:
    {{- include "golden-chart.labels" $ | nindent 4 }}
    {{- with $gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $.Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- toYaml $gateway.selector | nindent 4 }}
  servers:
    {{- toYaml $gateway.servers | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
