{{- range $key, $secret := .Values.secrets }}
{{- if ne ($secret.enabled | toString) "false" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "golden-chart.resourceName" (dict "context" $ "component" $key) }}
  namespace: {{ include "golden-chart.namespace" $ }}
  labels:
    {{- include "golden-chart.labels" $ | nindent 4 }}
    {{- with $secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $.Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ $secret.type | default "Opaque" }}
{{- with $secret.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with $secret.stringData }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
