{{- if and .Values.serviceAccount (.Values.serviceAccount.create) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "golden-chart.serviceAccountName" . }}
  namespace: {{ include "golden-chart.namespace" . }}
  labels:
    {{- include "golden-chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if kindIs "bool" .Values.serviceAccount.automountServiceAccountToken }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end }}
